### ISSUE TITLE
Not installing on Windows

### ISSUE THREAD

**Issue by Nitwel** [HaikuTeam/animator#1050]
First of all, awesome that you guys are making this tool open source! ❤️ 
Right now I would love to start testing out your software but there is no prebuild version yet and I'm having a hard time running it locally. I know that this is kinda harsh to say but could you guys give an estimate on when the next release containing a windows version will come out as I'm just so excited to check it out.

I've followed all your steps on how to install it on Windows but I get greeted with this error.
```
E:\Programmieren\animator>yarn install
yarn install v1.13.0
[1/4] Resolving packages...
warning Resolution field "@types/node@10.12.30" is incompatible with requested version "@types/node@^8.0.24"
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @haiku/core@5.1.2" has unmet peer dependency "@angular/core@^6.0.9".
warning " > @haiku/core@5.1.2" has unmet peer dependency "react@^16.0.0 || ^15.4.2".
warning " > @haiku/core@5.1.2" has unmet peer dependency "react-dom@^16.0.0 || ^15.4.2".
warning "@haiku/core > @angular/core@6.1.10" has unmet peer dependency "zone.js@~0.8.26".
warning " > @haiku/player@3.0.4" has unmet peer dependency "react@^16.0.0 || ^15.4.2".
warning " > @haiku/player@3.0.4" has unmet peer dependency "react-dom@^16.0.0 || ^15.4.2".
warning "haiku-creator > better-react-spinkit@2.0.0-4" has unmet peer dependency "inline-style-prefixer@^2.0.1".
warning "haiku-creator > react-selectize@3.0.1" has incorrect peer dependency "react-transition-group@^1.1.2".
warning "haiku-creator > react-selectize@3.0.1" has unmet peer dependency "react-dom-factories@^1.0.0".
[4/4] Building fresh packages...
[-/6] ⠈ waiting...
[2/6] ⠈ electron
[3/6] ⠈ @ronomon/base64
[4/6] ⠈ nodegit
error E:\Programmieren\animator\node_modules\@ronomon\base64: Command failed.
Exit code: 7
Command: node-gyp rebuild
Arguments:
Directory: E:\Programmieren\animator\node_modules\@ronomon\base64
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.15.1 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'E:\\Programmieren\\animator\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\Programmieren\\animator\\node_modules\\@ronomon\\base64\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\Programmieren\\animator\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\nitwe\\.node-gyp\\8.15.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\nitwe\\.node-gyp\\8.15.1',
gyp info spawn args   '-Dnode_gyp_dir=E:\\Programmieren\\animator\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\nitwe\\.node-gyp\\8.15.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\Programmieren\\animator\\node_modules\\@ronomon\\base64',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\Programmieren\\animator\\node_modules\\@ronomon\\base64\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: Missing input files:
E:\Programmieren\animator\node_modules\@ronomon\base64\build\Release\binding.node
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:362:16)
gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:139:11)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:181:9)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Programmieren\\animator\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Programmieren\animator\node_modules\@ronomon\base64
gyp ERR! node -v v8.15.1
gyp ERR! node-gyp -v v3.8.0
```

**Comment by partytax** [comment]
Looks like there might be an issue with the `@ronomon\base64` package. Have you tried installing it ahead of time with `npm install --ignore-scripts @ronomon/base64`? That seems to be the method prescribed for Windows in the package README:
![2021-09-30_09-09-1633009589](https://user-images.githubusercontent.com/29897671/135467789-ad9ad95f-c3dd-4306-90d9-0b76c628bb0c.jpg)

**Comment by Nitwel** [comment]
running `yarn add --ignore-scripts @ronomon/base64 -W` resolved it though now I'm running into

```
PS E:\Programmieren\animator> yarn go
yarn run v1.13.0
$ yarn start default
$ node ./scripts/start.js default
fyi, your current branch is "master"


=============================================
running automatically with preset default
=============================================


=============================================
preparing to develop locally
=============================================


=============================================
first compiling everything
=============================================

$ node ./scripts/compile-all.js
No changes in testing since last compile. Skipping....
No changes in sdk-inkstone since last compile. Skipping....
No changes in sdk-client since last compile. Skipping....
No changes in cli since last compile. Skipping....
No changes in admin-cli since last compile. Skipping....
No changes in core since last compile. Skipping....
No changes in common since last compile. Skipping....
No changes in sdk-creator since last compile. Skipping....
No changes in ui-common since last compile. Skipping....
No changes in glass since last compile. Skipping....
No changes in formats since last compile. Skipping....
No changes in timeline since last compile. Skipping....
No changes in creator since last compile. Skipping....
No changes in plumbing since last compile. Skipping....

=============================================
starting local development
=============================================


=============================================
Note: NOT watching for code changes. To watch for code changes, run yarn watch-all in a new tab.
=============================================

$ E:\Programmieren\animator\node_modules\.bin\electron --inspect=9220 --remote-debugging-port=9222 .
E:\Programmieren\animator\node_modules\electron\index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (E:\Programmieren\animator\node_modules\electron\index.js:9:9)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Programmieren\animator\node_modules\electron\cli.js:3:16)
    at Module._compile (module.js:653:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by vsaiaditya** [comment]
I am also facing the same issue as @Nitwel .

**Comment by federico-hv** [comment]
@Nitwel your solution worked for me. Thanks! I didn't get the second error but it seems there's an issue with your local electron package. This could be due to network failing during installation. Some guys suggest to delete node_modules folder, clean npm or yarn cache and reinstall in verbose mode to get more info. Some mentioned having it solved by installing electron globally. The following links may be helpful...



https://github.com/electron/electron/issues/8466

https://stackoverflow.com/questions/42636151/electron-failed-to-install-correctly-please-delete-node-modules-and-try-instal

**Comment by Moretti-Federico** [comment]
Same issues for me

**Comment by Moretti-Federico** [comment]
If I start "just glass" or "just timeline" there are no errors but if I start "the whole chimichanga" the following errors are found:
VM66 module.js:543 Uncaught Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (VM66 module.js:543)
    at Function.Module._load (VM66 module.js:473)
    at Module.require (VM66 module.js:586)
    at Module.require (VM1108 ModuleWrapper.js:53)
    at require (VM67 module.js:11)
    at Object.<anonymous> (VM1473 nodegit.js:18)
    at Object.<anonymous> (VM1473 nodegit.js:1031)
    at Module._compile (VM66 module.js:642)
    at Object.Module._extensions..js (VM66 module.js:653)
    at Module.load (VM66 module.js:561)


it appears that the following variable is not created:
`var filename = Module._findPath(request, paths, isMain);
  if (!filename) {
    var err = new Error(`Cannot find module '${request}'`);
    err.code = 'MODULE_NOT_FOUND';
    throw err;
  }
  return filename;
};`

**Comment by Melvin-Abraham** [comment]
> running `yarn add --ignore-scripts @ronomon/base64 -W` resolved it though now I'm running into
> 
> ```
> PS E:\Programmieren\animator> yarn go
> yarn run v1.13.0
> $ yarn start default
> $ node ./scripts/start.js default
> fyi, your current branch is "master"
> 
> 
> =============================================
> running automatically with preset default
> =============================================
> 
> 
> =============================================
> preparing to develop locally
> =============================================
> 
> 
> =============================================
> first compiling everything
> =============================================
> 
> $ node ./scripts/compile-all.js
> No changes in testing since last compile. Skipping....
> No changes in sdk-inkstone since last compile. Skipping....
> No changes in sdk-client since last compile. Skipping....
> No changes in cli since last compile. Skipping....
> No changes in admin-cli since last compile. Skipping....
> No changes in core since last compile. Skipping....
> No changes in common since last compile. Skipping....
> No changes in sdk-creator since last compile. Skipping....
> No changes in ui-common since last compile. Skipping....
> No changes in glass since last compile. Skipping....
> No changes in formats since last compile. Skipping....
> No changes in timeline since last compile. Skipping....
> No changes in creator since last compile. Skipping....
> No changes in plumbing since last compile. Skipping....
> 
> =============================================
> starting local development
> =============================================
> 
> 
> =============================================
> Note: NOT watching for code changes. To watch for code changes, run yarn watch-all in a new tab.
> =============================================
> 
> $ E:\Programmieren\animator\node_modules\.bin\electron --inspect=9220 --remote-debugging-port=9222 .
> E:\Programmieren\animator\node_modules\electron\index.js:9
>   throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
>   ^
> 
> Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
>     at Object.<anonymous> (E:\Programmieren\animator\node_modules\electron\index.js:9:9)
>     at Module._compile (module.js:653:30)
>     at Object.Module._extensions..js (module.js:664:10)
>     at Module.load (module.js:566:32)
>     at tryModuleLoad (module.js:506:12)
>     at Function.Module._load (module.js:498:3)
>     at Module.require (module.js:597:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (E:\Programmieren\animator\node_modules\electron\cli.js:3:16)
>     at Module._compile (module.js:653:30)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

I also faced the same issue. In order to re-install electron properly, run the following command from the root of the project directory:

```console
$ node .\node_modules\electron\install.js
```

**Comment by Blendan1** [comment]
> If I start "just glass" or "just timeline" there are no errors but if I start "the whole chimichanga" the following errors are found: VM66 module.js:543 Uncaught Error: Cannot find module '../build/Debug/nodegit.node' at Function.Module._resolveFilename (VM66 module.js:543) at Function.Module._load (VM66 module.js:473) at Module.require (VM66 module.js:586) at Module.require (VM1108 ModuleWrapper.js:53) at require (VM67 module.js:11) at Object. (VM1473 nodegit.js:18) at Object. (VM1473 nodegit.js:1031) at Module._compile (VM66 module.js:642) at Object.Module._extensions..js (VM66 module.js:653) at Module.load (VM66 module.js:561)
> 
> it appears that the following variable is not created: `var filename = Module._findPath(request, paths, isMain); if (!filename) { var err = new Error(`Cannot find module '${request}'`); err.code = 'MODULE_NOT_FOUND'; throw err; } return filename; };`

Have you been able to solve this issue? Im running into the same problem and im stuck

**Comment by federico-hv** [comment]
@Blendan1 I was having this issue on MacOS, maybe my fix works for you. If you check the `package.json` on `packages/haiku-plumbing` it seems the version of nodegit is `"0.20.3"` this was causing the same issue for me (don't remember why). I fixed it by uninstalling this version and installing the latest version of nodegit at that time which was "0.23.0". If you run today `npm view nodegit versions` you will see the "0.26.4" as the last stable version so that one might work too. To summarize:

1. `cd packages/haiku-plumbing`
2. `npm uninstall nodegit` (will remove the 0.20.3)
3. `npm install nodegit` (should install the latest stable). Check final version on the package.json file and if it's still throwing the error try `npm install nodegit@0.23.0` (worked for me).

I also recommend you check out [Rive](https://rive.app/) which solved some problems Lottie was having and made it simple to create more complex animations with really good performance for multiple devices.
