### ISSUE TITLE
can't install dependencies because of 503 error

### ISSUE THREAD

**Issue by jdwilkin** [HaikuTeam/animator#1055]
when attempting to install via yarn I am getting this error:

error An unexpected error occurred: "https://reservoir.haiku.ai:8910/@haiku%2fplayer/-/player-3.0.4.tgz: Request failed \"503 Service Unavailable\"".

**Comment by gumptious** [comment]
This should be resolvable by removing the `.npmrc` file in the root of the project and trying a fresh `yarn`. The `reservoir` service was intentionally and permanently shut down.

If you can confirm removing the file works, we'd happily accept a PR of the removal.

**Comment by jdwilkin** [comment]
removing the .npmrc file and the yarnrc file plus removing the yarn.lock entries that referenced the reservoir allowed it to install

I am now experiencing the following when trying to launch:

C:\projects\animator\node_modules\nodegit\dist\nodegit.js:15
    throw ex;
    ^

Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\projects\animator\node_modules\nodegit\build\Release\nodegit.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at Module.require (C:\projects\animator\packages\haiku-serialization\src\bll\ModuleWrapper.js:53:26)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\projects\animator\node_modules\nodegit\dist\nodegit.js:11:12)
Done in 8.69s.

**Comment by micaparat** [comment]
Also at same point in trying the windows version, any news?


D:\haiku\animator-master\node_modules\nodegit\dist\nodegit.js:15
    throw ex;
    ^

Error: A dynamic link library (DLL) initialization routine failed.
\\?\D:\haiku\animator-master\node_modules\nodegit\build\Release\nodegit.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at Module.require (D:\haiku\animator-master\packages\haiku-serialization\src\bll\ModuleWrapper.js:53:26)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\haiku\animator-master\node_modules\nodegit\dist\nodegit.js:11:12)
Done in 4.21s.
