### ISSUE TITLE
window problem with yarn electron rebuild

### ISSUE THREAD

**Issue by emergence75** [HaikuTeam/animator#1075]
after playing arround for some hours to the get a compiled windows exe, which finally worked. (the exe file still does not start but ok...)  
this is now a little bit longer
i've look into the issue with @ronomon\base64... 

the same issue is reproduceable for me when calling

PS F:\animator-5.1.2> yarn electron-rebuild
`yarn run v1.13.0
$ F:\animator-5.1.2\node_modules\.bin\electron-rebuild
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.15.1 | win32 | x64
gyp info spawn C:\Users\root\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'F:\\animator-5.1.2\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\animator-5.1.2\\node_modules\\@ronomon\\base64\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\animator-5.1.2\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\root\\.electron-gyp\\iojs-2.0.8\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\root\\.electron-gyp\\iojs-2.0.8',
gyp info spawn args   '-Dnode_gyp_dir=F:\\animator-5.1.2\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\root\\.electron-gyp\\iojs-2.0.8\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=F:\\animator-5.1.2\\node_modules\\@ronomon\\base64',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'F:\\animator-5.1.2\\node_modules\\@ronomon\\base64\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: Missing input files:
F:\animator-5.1.2\node_modules\@ronomon\base64\build\Release\binding.node
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
F:\animator-5.1.2\node_modules\@ronomon\base64\build\binding.vcxproj(20,3): error MSB4019: The imported project "F:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (F:\animator-5.1.2\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\versions\\v8.15.1\\node.exe" "F:\\animator-5.1.2\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=2.0.8" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--msvs_version=2015"
gyp ERR! cwd F:\animator-5.1.2\node_modules\@ronomon\base64
gyp ERR! node -v v8.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.15.1 | win32 | x64
gyp info spawn C:\Users\root\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'F:\\animator-5.1.2\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\animator-5.1.2\\node_modules\\@ronomon\\base64\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\animator-5.1.2\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\root\\.electron-gyp\\iojs-2.0.8\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\root\\.electron-gyp\\iojs-2.0.8',
gyp info spawn args   '-Dnode_gyp_dir=F:\\animator-5.1.2\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\root\\.electron-gyp\\iojs-2.0.8\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=F:\\animator-5.1.2\\node_modules\\@ronomon\\base64',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'F:\\animator-5.1.2\\node_modules\\@ronomon\\base64\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: Missing input files:
F:\animator-5.1.2\node_modules\@ronomon\base64\build\Release\binding.node
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
F:\animator-5.1.2\node_modules\@ronomon\base64\build\binding.vcxproj(20,3): error MSB4019: The imported project "F:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (F:\animator-5.1.2\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\versions\\v8.15.1\\node.exe" "F:\\animator-5.1.2\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=2.0.8" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--msvs_version=2015"
gyp ERR! cwd F:\animator-5.1.2\node_modules\@ronomon\base64
gyp ERR! node -v v8.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (F:\animator-5.1.2\node_modules\spawn-rx\lib\src\index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (F:\animator-5.1.2\node_modules\rxjs\internal\Subscriber.js:207:16)
    at SafeSubscriber.error (F:\animator-5.1.2\node_modules\rxjs\internal\Subscriber.js:158:26)
    at Subscriber._error (F:\animator-5.1.2\node_modules\rxjs\internal\Subscriber.js:92:26)
    at Subscriber.error (F:\animator-5.1.2\node_modules\rxjs\internal\Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (F:\animator-5.1.2\node_modules\rxjs\internal\Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (F:\animator-5.1.2\node_modules\rxjs\internal\Subscriber.js:72:18)
    at SafeSubscriber._next (F:\animator-5.1.2\node_modules\spawn-rx\lib\src\index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (F:\animator-5.1.2\node_modules\rxjs\internal\Subscriber.js:207:16)
    at SafeSubscriber.next (F:\animator-5.1.2\node_modules\rxjs\internal\Subscriber.js:145:22)
error Command failed with exit code 4294967295.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

when checking the directory 
F:\animator-5.1.2\node_modules\@ronomon\base64\build
there is no Release folder with files in it...

now comes the interesting part...
electron-rebuild uses node-gyp to process F:\animator-5.1.2\node_modules\@ronomon\base64 => binding.gyp

good...

the package compiles on windows when switching direct to the folder...
PS F:\animator-5.1.2> cd node_modules/@ronomon/base64
PS F:\animator-5.1.2\node_modules\@ronomon\base64> node-gyp rebuild

i get following 
PS F:\animator-5.1.2> cd node_modules/@ronomon/base64
PS F:\animator-5.1.2\node_modules\@ronomon\base64> node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@8.15.1 | win32 | x64
gyp info find Python using Python version 2.7.18 found at "C:\Python27\python.exe"
gyp info find VS using VS2019 (16.8.30907.101) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\root\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\animator-5.1.2\\node_modules\\@ronomon\\base64\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\root\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\root\\AppData\\Local\\node-gyp\\Cache\\8.15.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\root\\AppData\\Local\\node-gyp\\Cache\\8.15.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\root\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\root\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\8.15.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=F:\\animator-5.1.2\\node_modules\\@ronomon\\base64',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'F:\\animator-5.1.2\\node_modules\\@ronomon\\base64\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: Missing input files:
F:\animator-5.1.2\node_modules\@ronomon\base64\build\Release\binding.node
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "-m" hinzufügen.
  binding.cc
  win_delay_load_hook.cc
     Bibliothek "F:\animator-5.1.2\node_modules\@ronomon\base64\build\Release\binding.lib" und Objekt "F:\animator-5.1.2\node_modules\@ronomon\base64\build\Release\binding.exp" werden erstellt.
  Code wird generiert.
  Previous IPDB not found, fall back to full compilation.
  All 101 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Codegenerierung ist abgeschlossen.
  binding.vcxproj -> F:\animator-5.1.2\node_modules\@ronomon\base64\build\Release\\binding.node
  Copying F:\animator-5.1.2\node_modules\@ronomon\base64/build/Release/binding.node to F:\animator-5.1.2\node_modules\@ronomon\base64
          1 Datei(en) kopiert.
gyp info ok

checking the folder node_modules\@ronomon\base64\build\Release\ exists with all needed files for compiling...

switching back
PS F:\animator-5.1.2\node_modules\@ronomon\base64> cd ../../../
and calling it from there 
PS F:\animator-5.1.2> node-gyp rebuild
fails.. like it does inside electron-rebuild

PS F:\animator-5.1.2> node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@8.15.1 | win32 | x64
gyp info find Python using Python version 2.7.18 found at "C:\Python27\python.exe"
gyp info find VS using VS2019 (16.8.30907.101) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\root\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\animator-5.1.2\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\root\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\root\\AppData\\Local\\node-gyp\\Cache\\8.15.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\root\\AppData\\Local\\node-gyp\\Cache\\8.15.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\root\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\root\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\8.15.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=F:\\animator-5.1.2',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'F:\\animator-5.1.2\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: F:\animator-5.1.2) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\root\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\versions\\v8.15.1\\node.exe" "C:\\Users\\root\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\animator-5.1.2
gyp ERR! node -v v8.15.1
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok

so far so good...

calling it with
PS F:\animator-5.1.2> node-gyp rebuild --directory=node_modules/@ronomon/base64/
works like it should.... compiles and everything is fine...

i've looked and search the code for some hours, but i do not found the position to add this parameter to the electron-rebuild
(--directory=node_modules/@ronomon/base64/)
electron does only add -Dmodule_root_dir=F:\\animator-5.1.2\\node_modules\\@ronomon\\base64',

i think by solving this issue, there should be no need to call
yarn add --ignore-scripts @ronomon/base64 -W
before when calling
yarn compile-all

thx for help

**Comment by emergence75** [comment]
oops.. there seems to be a general problem with electron and node-gyp on windows...
nodegit does also not compile...

thats the reason for also for this message (start the exe file or trying yarn go)

Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at Module.f.require (F:\animator-master\dist\win-unpacked\resources\app.asar\node_modules\haiku-serialization\src\bll\ModuleWrapper.js:1:1028)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\animator-master\dist\win-unpacked\resources\app.asar\node_modules\nodegit\dist\nodegit.js:18:12)
    at Object.<anonymous> (F:\animator-master\dist\win-unpacked\resources\app.asar\node_modules\nodegit\dist\nodegit.js:1031:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)

**Comment by emergence75** [comment]
so after reading 
https://www.electronjs.org/de/docs/latest/tutorial/using-native-node-modules

i've checked to compile against the correct electron headers...

PS F:\animator-5.1.2> cd ./node_modules/nodegit/
PS F:\animator-5.1.2> node-gyp rebuild --target=2.0.8 --arch=x64 --dist-url=https://electronjs.org/headers
PS F:\animator-5.1.2> cd ../../../
PS F:\animator-5.1.2> cd ./node_modules/@ronomon/base64/
PS F:\animator-5.1.2> node-gyp rebuild --target=2.0.8 --arch=x64 --dist-url=https://electronjs.org/headers
PS F:\animator-5.1.2> cd ../../../

PS F:\animator-5.1.2> node .\node_modules\electron\install.js

PS F:\animator-5.1.2> yarn go
  
app starts up on windows

the windows installer still does not work...
the routine removes both folders 
/node_modules/@ronomon/base64/build/Release 
/node_modules/nodegit/build/Release 
and the exe file crashes...

by the way, nice app...

**Comment by saifi419c** [comment]
I've been waiting for soo long and nobody came up with any solution that is understandable for a no-code user. I guess you've done it and made it work. can you guide me on what should I do to make the app work? it will be huge for me as I can't a good alternative to this app. **Thanks in advance.**

**Comment by emergence75** [comment]
in the meantime i succeeded to create a running windows installer... i'll post the link for downloading in the next days...
a description for what i did, to create this thing is a little bit complicated, 'cause of this bug here... does anyone know a free file sharing platform to upload the installer ?

**Comment by Arch-Unique** [comment]
You could use mediafire.com ... I will gladly appreciate

**Comment by yash-moon** [comment]
Yes mediafire.com is good or here are some good alternatives - 
1. Download.gg
2. https://send.vis.ee/ 
3. filetransfer.io
🙂

**Comment by saifi419c** [comment]
@emergence75 You are the savior sir. Really appreciate your work. you are the king. Here's the crown 👑🙂

**Comment by emergence75** [comment]
thanks for the urls... using send.vis.ee
here we go... 

https://send.vis.ee/download/3c0423cbbfda8854/#4wnYcvrhIgDH7TKj4cTTqA

valid for 7 days...

**Comment by yash-moon** [comment]
> thanks for the urls... using send.vis.ee here we go...
> 
> https://send.vis.ee/download/3c0423cbbfda8854/#4wnYcvrhIgDH7TKj4cTTqA
> 
> valid for 7 days...

Looks like the link expired😅I think its set to expire after 1 download by default,
can you please verify ?

**Comment by saifi419c** [comment]
I have uploaded it to my drive. you can download it here.

https://drive.google.com/file/d/1EKHI51lNAroNzp3hiAYpl3_weShQ5lwy/view?usp=sharing

**Comment by yash-moon** [comment]
> 

that's great, thanks 👍

**Comment by Yara-UC** [comment]
Thank you so much for this! I tried installing this a few months just following the README and it was the must frustrating experience, so this is a godsend

**Comment by emergence75** [comment]
i had no time to play arround with this app... did the installer work you ?
and has someone of you created some demo animations to look at ?

**Comment by mandicOfisl** [comment]
@emergence75 The installer worked just fine for me and for that, I thank you!

Unfortunately, only Lottie files are successfully exported. Video and GIF (medium & high quality) export do not work. "Save file" dialog is shown, but the file is not created.

In my case, Lottie export is the reason I wanted this app so I don't care much about video and GIF export, but still...

**Comment by saifi419c** [comment]
It worked fine. But the app is missing some functions and not well designed
for windows. I quit and started using adobe after effects. But you did
great

**Comment by adenirantayo** [comment]
Hello, I was able to install the windows built but, I can't create a project, I kept getting a popup message that I should connect to the internet, even though I was connected to the internet

**Comment by emergence75** [comment]
[@mandicOfisl](https://github.com/mandicOfisl) i played arround a little bit and thanks for the hint. the ffmpeg.exe file is missing in the installer... i needed to change the package.json... had no better idea to add the suffix by hand
"node_modules/ffmpeg-static/bin/${platform}/${arch}/ffmpeg.exe"

[@saifi419c](https://github.com/saifi419c) i'll send you a link, with the changed installer as soon as you respond. so that you can update the google drive file...

**Comment by emergence75** [comment]
https://download.gg/de/file-13432894_ba1b52552250acf3

**Comment by adenirantayo** [comment]
> https://download.gg/de/file-13432894_ba1b52552250acf3
![Haiku Capture](https://user-images.githubusercontent.com/25295202/166184261-bd8fa45b-ceba-49ae-8cc2-7cc8da4333c1.JPG)
![Ha Capture](https://user-images.githubusercontent.com/25295202/166184284-fb0cd111-be1c-449b-842a-6c91a29c6371.JPG)
Hello, after downloading this latest built of Haiku, i got an error message. I have uploaded the popup message.
Thank you

**Comment by infoengine1337** [comment]
> [https://download.gg/de/file-13432894_ba1b52552250acf3 ](https://download.gg/de/file-13432894_ba1b52552250acf3)

Could you please re-upload this file again?
Thank you for your work.

**Comment by emergence75** [comment]
Download my files with this link : https://download.gg/en/file-14770349_ba1b52552250acf3

**Comment by infoengine1337** [comment]
> このリンクで私のファイルをダウンロードしてください: https://download.gg/en/file-14770349_ba1b52552250acf3


Thank you very much.

**Comment by danigrs** [comment]
Could you please re-upload your download again? Thank you very much.

**Comment by fahabib** [comment]
@emergence75  Can you please provide me .exe working video and gif export

**Comment by emergence75** [comment]
https://download.gg/en/file-16134434_8b404d9d717117a5

**Comment by fahabib** [comment]
Thank you bro

**Comment by lmfff** [comment]
Could you upload it again?

**Comment by fahabib** [comment]
Download from here : https://drive.google.com/file/d/18uin3-Cydog9X2sI08xIoC-TQrykqvj2/view?usp=sharing
