### ISSUE TITLE
SyntaxError: invalid syntax     'uv_library%': 'static_library',

### ISSUE THREAD

**Issue by mujehoxe** [HaikuTeam/animator#1107]
[4/4] Building fresh packages...
[-/6] ⢀ waiting...
[-/6] ⢀ waiting...
[3/6] ⢀ @ronomon/base64
[4/6] ⢀ nodegit
error /home/o/animator/node_modules/@ronomon/base64: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/o/animator/node_modules/@ronomon/base64
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@18.16.1 | linux | x64
gyp http GET https://nodejs.org/download/release/v18.16.1/node-v18.16.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v18.16.1/node-v18.16.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v18.16.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v18.16.1/SHASUMS256.txt
(node:731011) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/home/o/animator/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/o/animator/node_modules/@ronomon/base64/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/o/animator/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/o/.node-gyp/18.16.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/o/.node-gyp/18.16.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/o/animator/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/o/.node-gyp/18.16.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/o/animator/node_modules/@ronomon/base64',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/home/o/animator/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/home/o/animator/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/home/o/animator/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/home/o/animator/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "/home/o/animator/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "/home/o/animator/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2783, in Load
    variables, includes, depth, check, True)
  File "/home/o/animator/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 399, in LoadTargetBuildFile
    includes, True, check)
  File "/home/o/animator/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 271, in LoadOneBuildFile
    aux_data, includes, check)
  File "/home/o/animator/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 308, in LoadBuildFileIncludesIntoDict
    LoadOneBuildFile(include, data, aux_data, None, False, check),
  File "/home/o/animator/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 251, in LoadOneBuildFile
    None)
  File "/home/o/.node-gyp/18.16.1/include/node/common.gypi", line 1
    'uv_library%': 'static_library',
                 ^
SyntaxError: invalid syntax
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/o/animator/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 6.3.8-100.fc37.x86_64
gyp ERR! command "/usr/bin/node-18" "/home/o/animator/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/o/animator/node_modules/@ronomon/base64
gyp ERR! node -v v18.16.1

**Comment by keithrbennett** [comment]
I get this same error when running `yarn install` on my Ruby on Rails project.
